[2024-09-19T18:13:44.655+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-19T18:13:45.148+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-09-19T18:13:45.180+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-19T18:13:47.955+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-18 00:00:00+00:00
[2024-09-19T18:13:49.568+0000] {standard_task_runner.py:57} INFO - Started process 425 to run task
[2024-09-19T18:13:49.851+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmp6p04xmeu']
[2024-09-19T18:13:49.931+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask submit_tables
[2024-09-19T18:13:54.562+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables scheduled__2024-09-18T00:00:00+00:00 [running]> on host 48913e9acee9
[2024-09-19T18:14:14.217+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-09-19T18:14:17.595+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff85a7e8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-19T18:14:20.919+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240918T000000, start_date=20240919T181344, end_date=20240919T181420
[2024-09-19T18:14:24.748+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-19T18:14:37.178+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
