[2024-09-19T18:13:44.450+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T18:13:46.683+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T18:13:46.929+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-19T18:13:48.564+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-17 00:00:00+00:00
[2024-09-19T18:13:49.763+0000] {standard_task_runner.py:57} INFO - Started process 428 to run task
[2024-09-19T18:13:50.634+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpcox1shv1']
[2024-09-19T18:13:51.534+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask submit_tables
[2024-09-19T18:13:54.457+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables scheduled__2024-09-17T00:00:00+00:00 [running]> on host 48913e9acee9
[2024-09-19T18:14:28.717+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-09-19T18:14:31.797+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff85a76f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-19T18:14:33.795+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240917T000000, start_date=20240919T181344, end_date=20240919T181433
[2024-09-19T18:14:36.258+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-19T18:14:40.963+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
