[2024-09-19T18:13:45.408+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-15T00:00:00+00:00 [queued]>
[2024-09-19T18:13:47.794+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tables scheduled__2024-09-15T00:00:00+00:00 [queued]>
[2024-09-19T18:13:48.334+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-09-19T18:13:50.219+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tables> on 2024-09-15 00:00:00+00:00
[2024-09-19T18:13:50.643+0000] {standard_task_runner.py:57} INFO - Started process 430 to run task
[2024-09-19T18:13:51.349+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tables', 'scheduled__2024-09-15T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpzbqfx99_']
[2024-09-19T18:13:51.719+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask submit_tables
[2024-09-19T18:13:53.571+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tables scheduled__2024-09-15T00:00:00+00:00 [running]> on host 48913e9acee9
[2024-09-19T18:14:14.195+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='codewithyu' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-15T00:00:00+00:00'
[2024-09-19T18:14:15.111+0000] {pinot_table_operator.py:35} ERROR - An error occurred: HTTPConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /tables (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff85aa6310>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-09-19T18:14:21.485+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tables, execution_date=20240915T000000, start_date=20240919T181345, end_date=20240919T181421
[2024-09-19T18:14:27.383+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-09-19T18:14:38.867+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
